name: ar_flutter_reloaded
description: Flutter plugin for creating immersive and collaborative Augmented Reality (AR) experiences. Supports ARKit for iOS and ARCore for Android, enabling seamless cross-platform AR development with the latest Flutter and Android versions.
version: 0.0.1
#homepage: https://lars.carius.io
repository: https://github.com/CariusLars/ar_flutter_reloaded

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  vector_math: ^2.1.4
  json_annotation: ^4.9.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.thejenilgohel.ar_flutter_reloaded
        pluginClass: ArFlutterPlugin
      ios:
        pluginClass: ArFlutterPlugin
